name: live_teacher
version: 0.1.0
description: Live-Teacher Flutter App
publish_to: 'none'
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.0.0
  firebase_auth: ^4.0.0
  cloud_firestore: ^4.0.0
  provider: ^6.0.0
  http: ^1.0.0
  file_picker: ^5.0.0
  flutter_tts: ^4.0.0
