# GitHub Actions CI for React Frontend

name: Frontend CI

on:
  push:
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend.yml'
  pull_request:
    paths:
      - 'frontend/**'
      - '.github/workflows/frontend.yml'

jobs:
  build-and-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: |
          cd frontend
          npm install
      - name: Lint
        run: |
          cd frontend
          npm run lint || true  # Replace with actual lint script
      - name: Build
        run: |
          cd frontend
          npm run build || true  # Replace with actual build script
